In [1]:
import pandas as pd

# Series

In [2]:
data = [1,2,3,4,5]

In [4]:
s = pd.Series(data)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
index = ['Linea' + str(i) for i in range(5)]
index
# Nombres de los nuevos indices

['Linea0', 'Linea1', 'Linea2', 'Linea3', 'Linea4']

In [9]:
s = pd.Series(data = data, index = index)
s
# Asigna los nuevos indices a los valores

Linea0    1
Linea1    2
Linea2    3
Linea3    4
Linea4    5
dtype: int64

In [11]:
data = {'Linea' + str(i) : i+1 for i in range(5)}
data
# Trabajando con diccionarios

{'Linea0': 1, 'Linea1': 2, 'Linea2': 3, 'Linea3': 4, 'Linea4': 5}

In [12]:
s = pd.Series(data)
s

Linea0    1
Linea1    2
Linea2    3
Linea3    4
Linea4    5
dtype: int64

In [14]:
s1 = s + 2
s1
# Aumenta 2 a cada valor de la serie

Linea0    3
Linea1    4
Linea2    5
Linea3    6
Linea4    7
dtype: int64

In [15]:
s2 = s1 + s
s2
# Suma entre series

Linea0     4
Linea1     6
Linea2     8
Linea3    10
Linea4    12
dtype: int64

Ejercicios

In [21]:
datos = {'A': {'X': 1, 'Y': 3}, 'B': {'X': 2, 'Y': 4}}
df = pd.DataFrame(datos)
df

   A  B
X  1  2
Y  3  4

In [22]:
datos = [[1, 2, 3], [4, 5, 6]]
index = 'X,Y'.split(',')
columns = list('CBA')[::-1]
df = pd.DataFrame(datos, index, columns)
df

   A  B  C
X  1  2  3
Y  4  5  6

# Dataframe

In [23]:
data = [[1,2,3,],[4,5,6],[7,8,9]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [26]:
df1 = pd.DataFrame(data = data)
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [28]:
index = ['Linea' + str(i) for i in range(3)]
index
# Crear el nombre de los renglones

['Linea0', 'Linea1', 'Linea2']

In [29]:
df1 = pd.DataFrame(data = data, index = index)
df1

        0  1  2
Linea0  1  2  3
Linea1  4  5  6
Linea2  7  8  9

In [30]:
columns = ['Columna' + str(i) for i in range(3)]
columns
# Crear el nombre de las columnas

['Columna0', 'Columna1', 'Columna2']

In [31]:
df1 = pd.DataFrame(data = data, index = index, columns = columns)
df1

        Columna0  Columna1  Columna2
Linea0         1         2         3
Linea1         4         5         6
Linea2         7         8         9

In [46]:
## Convertir un diccionario a dataframe

In [39]:
data = {'Columna0': {'Linea0': 1,'Linea1': 4,'Linea2': 7},
 'Columna1': {'Linea0': 2,'Linea1': 5,'Linea2': 8},
 'Columna2': {'Linea0': 3,'Linea1': 6,'Linea2': 9}}
data

{'Columna0': {'Linea0': 1, 'Linea1': 4, 'Linea2': 7},
 'Columna1': {'Linea0': 2, 'Linea1': 5, 'Linea2': 8},
 'Columna2': {'Linea0': 3, 'Linea1': 6, 'Linea2': 9}}

In [41]:
df2 = pd.DataFrame(data)
df2

        Columna0  Columna1  Columna2
Linea0         1         2         3
Linea1         4         5         6
Linea2         7         8         9

In [ ]:
# COnvertir una tupla a dataframe

In [42]:
data2 = [(1,2,3),(4,5,6,),(7,8,9)]
data2

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [55]:
df3 = pd.DataFrame(data, index = index, columns = columns)
df3

        Columna0  Columna1  Columna2
Linea0         1         2         3
Linea1         4         5         6
Linea2         7         8         9

In [48]:
df1[df1 > 0] = 'A'
df1

       Columna0 Columna1 Columna2
Linea0        A        A        A
Linea1        A        A        A
Linea2        A        A        A

In [49]:
df2[df2 > 0] = 'B'
df2

       Columna0 Columna1 Columna2
Linea0        B        B        B
Linea1        B        B        B
Linea2        B        B        B

In [56]:
df3[df3 > 0] = 'C'
df3

       Columna0 Columna1 Columna2
Linea0        C        C        C
Linea1        C        C        C
Linea2        C        C        C

In [57]:
df4 = pd.concat([df1,df2,df3])
df4
# Concatena los dataframes

       Columna0 Columna1 Columna2
Linea0        A        A        A
Linea1        A        A        A
Linea2        A        A        A
Linea0        B        B        B
Linea1        B        B        B
Linea2        B        B        B
Linea0        C        C        C
Linea1        C        C        C
Linea2        C        C        C

In [58]:
df5 = pd.concat([df1,df2,df3], axis = 1)
df5
# Invierte los ejes

,Columna0,Columna1,Columna2,Columna0,Columna1,Columna2,Columna0,Columna1,Columna2
Linea0,A,A,A,B,B,B,C,C,C
Linea1,A,A,A,B,B,B,C,C,C
Linea2,A,A,A,B,B,B,C,C,C